@startuml
!include style.puml

scale 1.5

skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage{
Interface XYZStorage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface XYZBookStorage <<Interface>>

Class StorageXYZManager
Class JsonUserPrefsStorage
Class JsonXYZBookStorage

StorageXYZManager .left.|> XYZStorage
StorageXYZManager o-right-> UserPrefsStorage
StorageXYZManager o--> XYZBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonXYZBookStorage .left.|> XYZBookStorage
JsonXYZBookStorage .down.> JsonSerializableXYZBookStorage
JsonSerializableXYZBookStorage .right.> JsonSerializableXYZ
JsonSerializableXYZ .right.> JsonAdaptedXYZ
note right of JsonXYZBookStorage : XYZ = Deliverable, \nMeeting or Person
}
@enduml
