@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface ABCStorage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface ABCBookStorage <<Interface>>

Class StorageABCManager
Class JsonUserPrefsStorage
Class JsonABCBookStorage

StorageABCManager .left.|> ABCStorage
StorageABCManager o-right-> UserPrefsStorage
StorageABCManager o--> ABCBookStorage

JsonUserPrefsStorage .left.|> UserPrefsStorage
JsonABCBookStorage .left.|> ABCBookStorage
JsonABCBookStorage .down.> JsonSerializableABCBookStorage
JsonSerializableABCBookStorage .right.> JsonSerializableABC
JsonSerializableABC .right.> JsonAdaptedABC

note top of JsonSerializableABC: JsonSerializableABC = JsonSerializableDeliverable\nJsonSerializabeMeeting, JsonSerializablePerson
@enduml
