@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class StatusBarFooter
Class CommandBox
package XYZ <<Rectangle>>{
Class XYZDetailsPanel
Class XYZListPanel
Class XYZCard
}
package DashBoard <<Rectangle>>{
Class CalendarDeliverableCard
Class CalendarListPanel
Class CalendarMeetingCard
Class ProjectCompletionStatusPanel
}
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> MainWindow
MainWindow --> HelpWindow
MainWindow *-down-> CommandBox
MainWindow *-down-> ResultDisplay
MainWindow *-down-> XYZListPanel
MainWindow *-down-> StatusBarFooter
MainWindow *-down-> XYZDetailsPanel
MainWindow *-down-> CalendarListPanel
MainWindow *-down-> ProjectCompletionStatusPanel

XYZListPanel -down-> XYZCard
CalendarListPanel -down-> CalendarDeliverableCard
CalendarListPanel -down-> CalendarMeetingCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
XYZListPanel --|> UiPart
XYZCard --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow -down-|> UiPart
XYZDetailsPanel --|> UiPart
CalendarListPanel --|> UiPart
ProjectCompletionStatusPanel --|> UiPart

XYZCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic
note top of XYZ: XYZ = Deliverable, Meeting or Person

XYZListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart
@enduml
